const express = require('express');
const app = express();
const port = 3000;

app.set('view engine', 'ejs');
app.use(express.static('public'));


const produtos = [
  { id: 1, image: "https://m.media-amazon.com/images/I/61FTkkWMA9L._SY342_.jpg", nome: "Corrupt (devil's Night Livro 1)", descricao:"Nós esperamos. Fomos pacientes. E agora... cada um de seus pesadelos se tornaria realidade.", preco: 68.04, altor:"Edição Português | por Penelope Douglas", descricao1:"Sempre me disseram que os sonhos eram os desejos do nosso coração. Meus pesadelos, no entanto, acabaram se tornando minha obsessão.O nome dele é Michael Crist.O irmão mais velho do meu namorado se parece com aquele tipo de filme de terror, onde você cobre o rosto com as mãos, mas espia por entre os dedos. Ele é lindo, forte, e totalmente assustador. Sendo uma estrela do basquete profissional, assim como foi no time da faculdade, ele estava mais preocupado com a sujeira em sua sola de sapato do que comigo.Mas eu o notei.Eu o vi e ouvi. Todas as coisas que fez, as façanhas... Por anos, apenas roí minhas unhas, incapaz de afastar o meu olhar.Agora estava recém-formada no ensino médio e a caminho da faculdade, mas nem assim deixei de observar Michael.", descricao2: "Ele é mau, e toda as coisas ruins que vi já não podem permanecer apenas em minha mente.Porque ele finalmente percebeu minha existência.Michael: O nome dela é Erika Fane, mas todos a chamam de Rika.A namorada do meu irmão sempre frequentou minha casa, desde criança, e sua presença era constante à mesa do jantar. Todas as vezes que eu entrava na sala, ela abaixava o olhar, e mantinha-se imóvel quando eu me aproximava. Sempre pude detectar o medo que a rodeava, e mesmo que nunca tenha possuído seu corpo, eu sabia que possuía sua mente. E aquilo era tudo o que eu queria, de qualquer forma.Até que meu irmão se alistou no serviço militar, deixando Rika sozinha na universidade.Na minha cidade.Desprotegida.A oportunidade era boa demais para ser verdade, assim como o momento. Porque, sabe... três anos atrás ela colocou alguns dos meus amigos do colégio na cadeia, e agora eles estavam em liberdade.Nós esperamos. Fomos pacientes. E agora... cada um de seus pesadelos se tornaria realidade.Corrupt, é um romance ÚNICO com final próprio."},


  { id: 2, image: "https://m.media-amazon.com/images/I/616HZZs1uXL._SY342_.jpg", nome: "Hideaway (devil's Night Livro 2)", descricao:"Eu vi o seu refúgio. Está na hora de você ver o meu. Hideaway é um romance de suspense.", preco: 68.04, altor:"Edição Português | por Penelope Douglas", descricao1:"DEVIL'S NIGHT está de volta! Esconderijos secretos, perseguições, e todos os jogos outra vez...BANKS Imerso nas sombras da cidade, há um hotel chamado The Pope. Decadente, deserto e sombrio, encontra-se abandonado e rodeado por um mistério há muito esquecido. Mas você acha que é verdadeira, não é, Kai Mori? A história a respeito do décimo segundo andar. O mistério que cerca o hóspede sombrio que nunca se registrou para entrar ou sair. Você acha que vou ajudá-lo a encontrar o refúgio secreto para chegar até ele, não é?", descricao2:"Você e seus amigos podem até tentar me assustar. Podem tentar me pressionar. Porque mesmo que eu lute para disfarçar o que sinto quando você olha pra mim — desde adolescente —, acredito que talvez o que está procurando esteja mais perto do que imagina.Eu nunca vou traí-lo. Então se prepare. Na Devil’s Night, você será a caça. KAI Você não faz a menor ideia do que estou procurando, pequena. Você não sabe o que tive que fazer para sobreviver aos três anos na prisão, quando fui condenado por um crime que cometeria outra vez com o maior prazer. Ninguém pode saber o que me tornei. Eu quero aquele hotel, quero encontrá-lo e acabar logo com isso. Quero minha vida de volta. Mas quanto mais tempo passo ao seu lado, mais percebo que este novo eu é exatamente quem sempre fui destinado a ser. Então pode vir, garotinha. Não se acovarde. Minha casa fica na colina. Existem muitas maneiras de entrar, mas apenas com sorte você conseguirá sair. Eu vi o seu refúgio. Está na hora de você ver o meu."  },


  { id: 3, image: "https://m.media-amazon.com/images/I/61cj8JI4T9L._SY342_.jpg", nome: "Kill Switch Devil’s Night 3", descricao:"Como o novo homem da casa, agora teria livre acesso a ela. Kill Switch é um romance de suspense", preco: 75.21, altor:"Edição Português | por Penelope Douglas", descricao1:"“Eu faria algo muito pior do que aquilo que me levou à prisão. Ela não imagina como as coisas poderiam piorar.”WINTER Mandá-lo para a cadeia foi a pior coisa que já fiz. Não importava se ele havia cometido o crime ou que eu desejava que ele estivesse morto. Talvez eu tenha pensado que teria tempo suficiente para desaparecer antes que ele fosse solto, ou então que ele teria tomado jeito e se tornado alguém melhor.", descricao2:"Mas estava errada. Três anos se passaram rápido demais, e agora ele parecia pior do que nunca. A prisão apenas serviu para que ele tivesse tempo para elaborar um plano. E por mais que eu tenha previsto sua vingança, não esperava por isso. Ele não queria só me machucar. Ele queria acabar com tudo. DAMON Em primeiro lugar, eu acabaria com o pai dela. Foi ele quem afirmou a todos que eu a obriguei. Ele disse que sua garotinha havia sido uma vítima, mas eu era um garoto também, e ela quis tanto quanto eu. Segundo... acabar com qualquer possibilidade de fuga para ela, sua irmã e sua mãe. As mulheres Ashby estavam sozinhas agora, e desesperadas por um cavaleiro em uma armadura brilhante. Mas não era isso que elas encontrariam. Não, já era hora de dar ouvidos ao meu pai e assumir o controle do meu futuro. Era hora de mostrar a todos eles – minha família, a dela, aos meus amigos –, que eu nunca mudaria e que minha única ambição era me tornar o pesadelo de suas vidas. Começando com ela. Ela ficaria tão apavorada, que nem mesmo sua mente seria um lugar seguro quando eu a destruísse. E a melhor parte de tudo é que eu não precisaria invadir sua residência para fazer isso. Como o novo homem da casa, agora teria livre acesso a ela." },


  { id: 4, image: "https://m.media-amazon.com/images/I/510S2WZwJ+S._SY385_.jpg", nome: "Conclave Devil’S Night 3.5", descricao:"Encontraríamos Will. Nós consolidaríamos nossos planos, e acabaríamos com qualquer ameaça. Se sobrevivêssemos ao Conclave.", preco: 50.12, altor:"Edição Português | por Penelope Douglas", descricao1:"“Você sabe o que é um conclave papal?” DAMON Will estava desaparecido. Ninguém o via há meses, e as mensagens que chegavam de seu celular eram, com certeza, falsas. Algo estava errado. E precisávamos tomar uma atitude agora. Michael está prestes a destruir a enseada, Rika está escondendo alguma coisa, Evans Crist é uma ameaça e o pai de Winter continua sumido.", descricao2:"Todo mundo estava atordoado e sem saber o que fazer, totalmente vulneráveis. Era hora de agir. Era hora de reivindicar nosso lugar. RIKA Alguns anos atrás, nunca imaginei que estaria aqui. A bordo do Pithom. Em alto-mar. Sentada à mesa com Michael Crist, Kai Mori e Damon Torrance – homens que agora considerava como minha família. Havíamos nos isolado nesse iate até alinhar nossos planos, e só sairíamos daqui depois de tudo resolvido. Até mesmo segredos sobre os quais não queria falar, coisas que Michael desconhecia. Encontraríamos Will. Nós consolidaríamos nossos planos, e acabaríamos com qualquer ameaça. Se sobrevivêssemos ao Conclave."  },


  { id: 5, image: "https://m.media-amazon.com/images/I/51R657iiHBL._SY385_.jpg", nome: "Nightfall (Devil'S Night Livro 4)", descricao:"Um sorriso se espalha pelo meu rosto quando me lembro.Blackchurch abriga cinco prisioneiros. Eu sou apenas um de seus problemas.", preco: 82.38, altor:"Edição Português | por Penelope Douglas", descricao1:"O que acontece quando são cinco contra um e não há lugar para onde fugir? EMORY Eles a chamam de Blackchurch. Uma mansão isolada em uma localização desconhecida e remota, onde os ricos e poderosos enviam seus filhos desajustados para que esfriem a cabeça longe dos olhares indiscretos.Will Grayson sempre agiu como um animal. Irresponsável, selvagem e alguém que nunca se apegou a regras, fazendo sempre o que ele queria. De forma alguma, seu avô se arriscaria à humilhação de ver o nome da família na lama outra vez.", descricao2:"Mesmo que a última vez não tenha sido inteiramente sua culpa. Ele pode até ter gostado muito de me encurralar nos cantos dos corredores da escola quando ninguém estava olhando, para que ninguém percebesse que o Sr. Popular, na verdade, queria colocar a mão na pequena e pacata nerd que ele amava perturbar, mas... Ele também podia ser cordial. E cruel em uma tentativa de me proteger. A verdade é que... Ele tem todo o direito de me odiar. Aquilo tudo é minha culpa. Tudo. A Noite do Diabo. Os vídeos. As prisões. Eu sou culpada por tudo isto. E não me arrependo nem um pouco. WILL Eu nunca me importei em estar preso. Aprendi há muito tempo que ser tratado como um animal te dá permissão para agir como um. Ninguém nunca olhou para mim de outra forma. O único erro deles é achar que qualquer coisa que eu faça, é por acidente. Posso ficar aqui nesta casa sem Internet, televisão, bebidas ou garotas, mas sairei daqui com algo muito mais assustador para aqueles que são meus inimigos. Um plano. E uma nova matilha de lobos. Eu só não esperava que meus inimigos viessem até mim. Não faço ideia de quem a enfiou aqui dentro ou se realmente a intenção era deixá-la à minha mercê, mas posso farejá-la se escondendo pela casa. Ela está aqui. E quando a equipe de segurança vai embora depois de deixar os suprimentos, os portões se fecham e a porta da minha jaula é aberta, dando-me livre acesso à mansão e ao terreno da propriedade, por mais um mês sem supervisão alguma... Um sorriso se espalha pelo meu rosto quando me lembro... Blackchurch abriga cinco prisioneiros. Eu sou apenas um de seus problemas"  },


  { id: 6, image: "https://m.media-amazon.com/images/I/71qz7-CKo2L._SY385_.jpg", nome: "Fire Night (Devil'S Night Livro 6)", descricao:"A história se passa dez meses antes do epílogo de Nightfall.A trama é contada sob o ponto de vista de Kai, Damon, Will e Michael.", preco: 50.12, altor:"Edição Português | por Penelope Douglas", descricao1:"Já vimos a turma da Noite do Diabo aterrorizar geral. Agora, vamos vê-los entrar no espírito... As badaladas do relógio em St. Killian ressoam, enquanto sussurros flutuam escadaria acima. A neve pode ser vista caindo do céu escuro, através das janelas, e as velas cintilam e iluminam a noite mais longa do ano. A Noite do Diabo não é o único feriado que comemoramos. Esta noite, usaremos uma máscara diferente.", descricao2:"Alguns chamam de Solstício de inverno. Outros chamam de Natal. Nós a chamamos de Noite da Fogueira. A trama é contada sob o ponto de vista de Kai, Damon, Will e Michael"  },


  { id: 7, image: "https://m.media-amazon.com/images/I/618fXbK+OkL._SL1500_.jpg", nome: "Crepúsculo: (Série Crepúsculo): 1" , descricao:"Crepúsculo poderia ser uma história comum, não fosse um elemento irresistível: o objeto da paixão da protagonista é um vampiro. ", preco: 55.92 , altor:"Stephenie Meyer", descricao1:"Assim, soma-se à paixão um perigo sobrenatural temperado com muito suspense, e o resultado é uma leitura de tirar o fôlego. Um romance repleto das angústias e incertezas da juventude - o arrebatamento, a atração, a ansiedade que antecede cada palavra, cada gesto, e todos os medos. Isabella Swan chega à nublada e chuvosa cidadezinha de Forks - último lugar onde gostaria de viver. Tenta se adaptar à vida provinciana na qual aparentemente todos se conhecem, lidar com sua constrangedora falta de coordenação motora e se habituar a morar com um pai com quem nunca conviveu. Em seu destino está Edward Cullen. Lindo, perfeito, misterioso, ele é à primeira vista, hostil à presença de Bella - o que provoca nela uma inquietação desconcertante. Ela se apaixona. Ele, no melhor estilo amor proibido, alerta: Sou um risco para você. Ela é uma garota incomum. Ele é um vampiro. Ela precisa aprender a controlar seu corpo quando ele a toca.", descricao2:"Ele, a controlar sua sede pelo sangue dela. Em meio a descobertas e sobressaltos, Edward é, sim, perigoso: um perigo que qualquer mulher escolheria correr. Nesse universo fantasioso, os personagens construídos por Stephenie Meyer - humanos ou não - se mostram de tal forma familiares em seus dilemas e em seu comportamento que o sobrenatural parece real. Meyer torna perfeitamente plausível - e irresistível - a paixão de uma garota de 17 anos por um vampiro encantador. Com direitos vendidos para mais de 40 países e para o cinema, Crepúsculo chegou às telas em 2008, em filme assinado pelos produtores de O Diabo Veste Prada, protagonizado por Robert Pattinson e Kristen Stewart e dirigido por Catherine Hardwicke."  },


  { id: 8, image: "https://m.media-amazon.com/images/I/7153D5oFumL._SL1500_.jpg", nome: "Lua nova: (Série Crepúsculo):2", descricao:"O segundo livro da série que vendeu mais de 15 milhões de exemplares em todo o mundo, Lua nova alcançou o primeiro lugar na lista de mais vendidos do The New York Times.", preco: 50.63, altor:"Stephenie Meyer", descricao1:"Para Bella Swan, há um coisa mais importante do que a própria vida: Edward Cullen. Mas estar apaixonada por um vampiro é ainda mais perigoso do que ela poderia ter imaginado. Edward já resgatara Bella das garras de um monstro cruel, mas agora, quando o relacionamento ousado do casal ameaça tudo o que lhes é próximo e querido, eles percebem que seus problemas podem estar apenas começando...", descricao2:"Legiões de leitores que ficaram em transe com o best-seller Crepúsculo estão ávidos pela sequência da história de amor de Bella e Edward. Em Lua nova, Stephenie Meyer nos dá outra combinação irresistível de romance e suspense com um toque sobrenatural. Apaixonante e cheia de reviravoltas surpreendentes, essa saga de amor e vampiros segue rumo à imortalidade literária. Com direitos vendidos para mais de 40 países e para o cinema, Lua nova chegou às telas em 2009, em filme protagonizado por Kristen Stewart, Robert Pattinson e Taylor Lautner e dirigido por Chirs Weitz."  },


  { id: 9, image: "https://m.media-amazon.com/images/I/31zRy3HoV+L.jpg", nome: "Eclipse: (Série Crepúsculo): 3", descricao:"Enquanto Seattle é assolada por uma sequência de assassinatos misteriosos e uma vampira maligna continua em sua busca por vingança, Bella está cercada de perigos outra vez.", preco: 27.99, altor:"Stephenie Meyer", descricao1:"Em meio a isso, ela é forçada a escolher entre seu amor por Edward e sua amizade com Jacob - sabendo que essa decisão tem o potencial para reacender o conflito perene entre vampiros e lobisomens.", descricao2:"Com a proximidade da formatura, Bella tem mais uma decisão a tomar: vida ou morte. Mas o que representará cada uma dessas escolhas? Os leitores fascinados por Crepúsculo e Lua nova vão devorar ansiosamente Eclipse - o terceiro livro da excitante saga de amor e vampiros assinada por Stephenie Meyer."  },


  { id: 10, image: "https://m.media-amazon.com/images/I/71DW9z3UXkL._SL1500_.jpg", nome: "Amanhecer: (Série Crepúsculo): 4", descricao:"Estar irrevogavelmente apaixonada por um vampiro é tanto uma fantasia como um pesadelo, costurados em uma perigosa realidade para Bella Swan. ", preco: 25.99, altor:"Stephenie Meyer", descricao1:"Empurrada em uma direção por sua intensa paixão por Edward Cullen, e em outra por sua profunda ligação com o lobisomem Jacob Black, ela resistiu a um tumultuado ano de tentação, perda e conflito até o momento da decisão definitiva. A escolha entre fazer parte do obscuro, mas sedutor, mundo dos imortais ou permanecer vivendo como humana se tornou o marco que poderá transformar o destino dos dois clãs: vampiros e lobisomens.", descricao2:"Agora que Bella tomou sua decisão, uma corrente de acontecimentos sem precedentes se desdobrará, com consequências devastadoras. No momento em que as feridas parecem prontas para ser cicatrizadas, e os desgastantes confrontos da vida de Bella, resolvidos, isso pode significar a destruição. Para todos. Para sempre."  },
  

  { id: 11, image: "https://m.media-amazon.com/images/I/815mbcFisDL._SL1500_.jpg", nome: "Sol da meia-noite: (Midnight Sun) - Série Crepúsculo: 5", descricao:"Um dos maiores fenômenos editoriais dos últimos tempos, a saga Crepúsculo narra a icônica história de amor de Bella Swan, uma garota tímida e desastrada, que acaba de mudar de cidade, e Edward Cullen, um rapaz misterioso que esconde um segredo aterrorizante: é um vampiro.", preco: 39.99, altor:"Stephenie Meyer", descrição1:"Desde a primeira troca de olhares, ele fez tudo para ficar longe dela, mas e se as coisas não tiverem acontecido exatamente assim? Até agora, os leitores conheceram essa trama inesquecível apenas pelos olhos de Bella. No aguardado Sol da meia-noite, vamos testemunhar o nascimento desse amor pelo olhar de Edward, mergulhando em um universo novo, sombrio e surpreendente, cheio de revelações. Conhecer Bella foi o que aconteceu de mais irritante e instigante em todos os anos de Edward como vampiro.", descricao2:"À medida que conhecemos detalhes sobre seu passado e a complexidade de seus pensamentos, conseguimos entender por que Bella se tornou o eixo central de uma batalha decisiva em sua vida. Como Edward poderia seguir seu coração se isso significava colocar a amada em perigo? Do que ele seria capaz de abrir mão? Em Sol da meia-noite, Stephenie Meyer faz um retorno triunfal ao universo de Crepúsculo e nos transporta mais uma vez para Forks, convidando-nos a revisitar cada detalhe dessa história que conquistou milhões de fãs em todo o mundo. Em meio a uma paixão cercada de perigos sobrenaturais, vamos descobrir como Edward encara seus prazeres mais profundos e as consequências devastadoras de um amor proibido e imortal."  },
  

  { id: 12, image: "https://m.media-amazon.com/images/I/71-N-Y+irzL._SL1500_.jpg", nome: "Vida e morte", descricao:"Novamente, os leitores vão se apaixonar pela arrebatadora história de amor de Bella e Edward... ou, quem sabe, será uma primeira vez. A edição especial de aniversário inclui um conteúdo extra e exclusivo: Vida e morte, nova versão em que a autora inverte o gênero dos principais personagens.", preco: 62.91, altor:"Stephenie Meyer", descricao1:"Em Vida e morte os leitores vão se maravilhar com a experiência de ler a icônica saga de amor agora pelos olhos de um adolescente que se apaixona por uma sedutora vampira. Numa publicação ao estilo “vira-vira”, a edição comemorativa traz mais de 400 páginas de conteúdo extra, além da nova capa, com Crepúsculo de um lado e Vida e morte de outro. Os milhares de fãs de Bella e Edward não vão querer perder a oportunidade de ver seus tão queridos personagens em novos papéis.", descricao2:"“Fico maravilhada que já se tenham passado 10 anos da primeira edição de Crepúsculo”, comenta a autora Stephenie Meyer. “Para mim, esse aniversário é uma comemoração dos fãs, que sempre foram inacreditavelmente dedicados e apaixonados.”"  },
];

function buscarProdutoPorID(id){
    const produto = produtos.find(produto => produto.id == id);
    return produto || null
   }
   
app.get('/', (req, res) => {
  res.render('index', {produtos});
});

app.get('/produtos/:id', (req, res) => {
  const produto = buscarProdutoPorID(req.params.id)
  res.render('produtos', { produto });
});

app.listen(port, () => {
  console.log(`Servidor rodando em http://localhost:${port}`);
});